apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    tuan: test
    tuan2: test2
    tuan3: test3
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
